Question 1: (3.0 points) Create a random array A of size nXn (n≥2).
Create a view B of A and create a copy C of A.
Use the method "id()" to make sure B and C do not reference to the same location as A.

In [2]:
import numpy as np

Question 2: (1.0 points) Create a  checkerboard 8x8 matrix like (you can use tile function (tile())
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

Question 3: (2.0 points) Read the file "gdp_per_capita_ppp.csv" transforming it in a DataFrame with rows indexed by years and columns by the countrie and display the first 10 rows.

In [4]:
import pandas as pd

Question 4: (2.0 points) Graphically display the curve year  ××  GDP for the three countries with the largest sum of GDP over the whole set of years.

In [ ]:
import matplotlib.pyplot as plt

Question 5: (2.0 points) Print the name of all countries (if any) that contains no NaNs in their GDP series, that is, no missing data. Graphically display the series of those countries.