In [2]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3, 5)

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
print(a.ndim) #the number of axes (dimensions) of the array
print(a.shape) #a tuple of integers indicating the size of the array in each dimension
print(a.size) #the total number of elements of the array
print(a.dtype) # an object describing the type of the elements in the array
print(a.itemsize) #the size in bytes of each element of the array
print(a.data) #the buffer containing the actual elements of the array

2
(3, 5)
15
int64
8


In [7]:
a = np.array([1, 4, 5, 8])
print(a)

[1 4 5 8]


In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [9]:
print(a.dtype) # an object describing the type of the elements in the array


int64


In [10]:
b = np.array([1., 2., 3.])
#c = np.array([1, 2, 3], float) #explicity specify the data type too!
print(b.dtype)

float64


In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape[0]) #a tuple of integers indicating the size of the array in each dimension

2


In [14]:
np.arange(1, 9, 2) # start, end, step
#np.arange(10)

array([1, 3, 5, 7])

In [17]:
np.linspace(0, 1, 5) #different from numpy.arrange!

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [20]:
np.ones((3, 3))
np.zeros((2, 2))
np.identity(3) #indentity matrix
np.diag(np.array([1, 2, 3, 4])) #to change the elements of diagonal.

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [21]:
np.random.rand(3, 2)

array([[ 0.44244009,  0.58993307],
       [ 0.63025591,  0.64997813],
       [ 0.50673491,  0.20765148]])

In [16]:
list1 = [[1, 2, 3], [4, 5, 6]]
list1[1][2]

6

In [23]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a[(1, 2)]
a[1, 2]
a[-1,-1]
print(a)

[[1 2 3]
 [4 5 6]]


In [18]:
for row in a:
  print(row)

[1 2 3]
[4 5 6]


In [31]:
#Array slicing examples:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a[1, :])
#a[:, 2]
#a[-1]
a[:2, 1:]

[[1 2 3]
 [4 5 6]]
[4 5 6]


array([[2, 3],
       [5, 6]])

In [32]:
#ravel function
a=a.ravel()


In [33]:
#Reshape in desired way
c = a.reshape((3, 2))
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [34]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [35]:
np.transpose(x) #transposes matrix


array([[0, 2],
       [1, 3]])

In [44]:
a = np.arange(4*3*2).reshape(4, 3, 2)
print(a.shape)
print(a)
#a[0, 2, 1]
#5

b = a.transpose(1, 2, 0)
print(b.shape)
print(b)

(4, 3, 2)
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
(3, 2, 4)
[[[ 0  6 12 18]
  [ 1  7 13 19]]

 [[ 2  8 14 20]
  [ 3  9 15 21]]

 [[ 4 10 16 22]
  [ 5 11 17 23]]]


In [45]:
y

array([[[ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.]]])

In [26]:
#Assignment operation
a = np.arange(12)
b = a;
a[1] =5

In [27]:
b

array([ 0,  5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
b[1] = -2;
a

array([ 0, -2,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
a = np.array([[6, 4], [5, 9]])
sel = (a >= 6)
a[sel] = 0;
a

array([[0, 4],
       [5, 0]])

In [30]:
#View
a = np.array([[1, 2, 3], [4, 5, 6]])
a[:, 1:2] = 0
a


array([[1, 0, 3],
       [4, 0, 6]])

In [31]:
b = a.copy() #creating a copy

In [32]:
b

array([[1, 0, 3],
       [4, 0, 6]])

In [47]:
import pandas as p

In [34]:
index = ['a','b','c','d','e']
series = p.Series(np.arange(5), index=index) #
series

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [35]:
series[['a', 'c']] #how to access?

a    0
c    2
dtype: int64

In [36]:
#we can also use data to access the elements
series[2]

2

In [37]:
#Slicing
series['b':'e']

b    1
c    2
d    3
e    4
dtype: int64

In [38]:
#filtering the given data
filter = series >=3
series[filter]

d    3
e    4
dtype: int64

In [50]:
s = p.Series(['blue', 'purple', 'red'], index=[0,2,4]) #automatic alignment
s.reindex([2,3,1,0]) 

2    purple
3       NaN
1       NaN
0      blue
dtype: object

In [51]:
#s.reindex(range(5), fill_value='black')
s.reindex(range(5), method='ffill')

0      blue
1      blue
2    purple
3    purple
4       red
dtype: object

In [52]:
index1 = ['a','b','c']
index2 = ['a','b','d','e']
#sdata = {'b':100, 'c':150}
s1 = p.Series([1,2,3],index =index1 )
s2 = p.Series([3,4,5,7], index = index2)

In [42]:
s1+s2
#s1*2

a    4.0
b    6.0
c    NaN
d    NaN
e    NaN
dtype: float64

In [43]:
sdata = {'a':200, 'c':350}

s = p.Series(sdata) 
s

a    200
c    350
dtype: int64

In [44]:
#sorting series
#s.sort_values()
s.sort_index()

a    200
c    350
dtype: int64

In [45]:
s = p.Series([7, -5, 7, 4, 2, 0, 4])
s.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [46]:
s.rank(method= 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [47]:
data = p.DataFrame({ 'children': [4., 6, 3, 3, 2, 3, 5, 4],
                     'pet':      ['cat', 'dog', 'dog', 'fish', 'cat', 'dog', 'cat', 'fish'],
                     'salary':   [90, 24, 44, 27, 32, 59, 36, 27]})

In [48]:
data

children   pet  salary
0       4.0   cat      90
1       6.0   dog      24
2       3.0   dog      44
3       3.0  fish      27
4       2.0   cat      32
5       3.0   dog      59
6       5.0   cat      36
7       4.0  fish      27

In [49]:
data.salary
#data[['pet','salary']]

0    90
1    24
2    44
3    27
4    32
5    59
6    36
7    27
Name: salary, dtype: int64

In [50]:
data.ix[1]

children      6
pet         dog
salary       24
Name: 1, dtype: object

In [51]:
#adding the column is very easy
data['Other Pets']= np.nan

In [52]:
data

children   pet  salary  Other Pets
0       4.0   cat      90         NaN
1       6.0   dog      24         NaN
2       3.0   dog      44         NaN
3       3.0  fish      27         NaN
4       2.0   cat      32         NaN
5       3.0   dog      59         NaN
6       5.0   cat      36         NaN
7       4.0  fish      27         NaN

In [53]:
data.drop(['Other Pets'], axis=1)

children   pet  salary
0       4.0   cat      90
1       6.0   dog      24
2       3.0   dog      44
3       3.0  fish      27
4       2.0   cat      32
5       3.0   dog      59
6       5.0   cat      36
7       4.0  fish      27