# DS-GA-3001.001 Advanced Python
# Lecture 1: Python Recap

----
## <font color='blue'>Timing the code</font>
----

In [39]:
import time

t = time.process_time()
l1 = []
for i in range(100000):
    l1.append(i)
elapsed_time1 = time.process_time() - t
print(elapsed_time1)

t = time.process_time()
l1 = [i for i in range(100000)]
elapsed_time2 = time.process_time() - t
print(elapsed_time2)

if (elapsed_time1 > elapsed_time2):
    speed = elapsed_time1/elapsed_time2
    print('\"Comprehension\" is %.3f' %speed,'times faster than the \"for+append\"')
else:
    speed = elapsed_time2/elapsed_time1    
    print('\"for+append\" is %.3f' %speed,'times faster than the \"Comprehension\"')


0.02439399999999914
0.00916000000000139
"Comprehension" is 2.663 times faster than the "for+append"


In [40]:
import cProfile

def list_by_append():
    l1 = []
    for i in range(100000):
        l1.append(i)
        
def list_by_comprehension():
    l1 = [i for i in range(100000)]

cp = cProfile.Profile()
cp.enable()

list_by_append()
list_by_comprehension()

cp.disable()
cp.print_stats()


         100031 function calls in 0.059 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.002    0.002    0.048    0.048 <ipython-input-40-a7567dae838d>:14(<module>)
        1    0.003    0.003    0.011    0.011 <ipython-input-40-a7567dae838d>:15(<module>)
        1    0.000    0.000    0.000    0.000 <ipython-input-40-a7567dae838d>:17(<module>)
        1    0.033    0.033    0.046    0.046 <ipython-input-40-a7567dae838d>:3(list_by_append)
        1    0.000    0.000    0.008    0.008 <ipython-input-40-a7567dae838d>:8(list_by_comprehension)
        1    0.008    0.008    0.008    0.008 <ipython-input-40-a7567dae838d>:9(<listcomp>)
        3    0.000    0.000    0.000    0.000 codeop.py:132(__call__)
        3    0.000    0.000    0.000    0.000 hooks.py:142(__call__)
        3    0.000    0.000    0.000    0.000 hooks.py:207(pre_run_code_hook)
        3    0.000    0.000    0.000    0.000 interactiveshell.py:10

In [41]:
cProfile.run('list_by_append()')
cProfile.run('list_by_comprehension()')

         100004 function calls in 0.023 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.015    0.015    0.022    0.022 <ipython-input-40-a7567dae838d>:3(list_by_append)
        1    0.001    0.001    0.023    0.023 <string>:1(<module>)
        1    0.000    0.000    0.023    0.023 {built-in method builtins.exec}
   100000    0.007    0.000    0.007    0.000 {method 'append' of 'list' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}


         5 function calls in 0.009 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.007    0.007 <ipython-input-40-a7567dae838d>:8(list_by_comprehension)
        1    0.007    0.007    0.007    0.007 <ipython-input-40-a7567dae838d>:9(<listcomp>)
        1    0.002    0.002    0.009    0.009 <string>:1(<module>)
        1    0.000   

---
### File comprehensionXappend.py
```python
def list_by_append():
    l1 = []
    for i in range(100000):
        l1.append(i)

def list_by_comprehension():
    l1 = [i for i in range(100000)]

if __name__=="__main__":
    list_by_append()
    list_by_comprehension()
```

### the command
python3 -m cProfile -o timeStats.profile comprehensionXappend.py
### creates the file _timeStats.profile_ which can be analyzed via
python3 -m pstats timeStats.profile

----
## <font color='blue'>Numpy</font>
----

### Broadcasting

In [43]:
import cProfile 
import numpy as np

n = 10000
M = np.random.uniform(low=0,high=1,size=(n,n))
cProfile.run('M*2')  # the constant 2 is broadcasted in a n X n matrix

M2 = np.broadcast_to(2, (n,n)) # broadcasting manually the constant 2
cProfile.run('M*M2')

v = np.linspace(0,1,n)
cProfile.run('M - v') # v is broadcasted in a matrix before subtraction

Mv = np.broadcast_to(v, (n, n)) # broadcasting manually the array v
cProfile.run('M - Mv')

         3 function calls in 0.590 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.590    0.590    0.590    0.590 <string>:1(<module>)
        1    0.000    0.000    0.590    0.590 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}


         3 function calls in 0.642 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.642    0.642    0.642    0.642 <string>:1(<module>)
        1    0.000    0.000    0.642    0.642 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}


         3 function calls in 0.768 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.768    0.768    0.768    0.768 <string>:1(<module>)
        1  

### Slicing and assigments

In [49]:
A = np.arange(20).reshape(4,5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [50]:
B = A[:,:] # B is a view of A (not a copy nor a reference)

B[:2] = 0
print('Modifyin particular rows')
print(B,'\n')

B[:2,2:] = -1
print('Modifyin particular rows and columns')
print(B,'\n')

B[[0,2]][:,[2,4]] = -3 # fancy index does not modify B
print('Fancy index')
print(B,'\n')

B[[0,2],[2,4]] = -3  # why is B modified now?
print('Fancy index with replacement')
print(B,'\n')

print('The content of A is also modified')
print(A)


Modifyin particular rows
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

Modifyin particular rows and columns
[[ 0  0 -1 -1 -1]
 [ 0  0 -1 -1 -1]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

Fancy index
[[ 0  0 -1 -1 -1]
 [ 0  0 -1 -1 -1]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

Fancy index with replacement
[[ 0  0 -3 -1 -1]
 [ 0  0 -1 -1 -1]
 [10 11 12 13 -3]
 [15 16 17 18 19]] 

The content of A is also modified
[[ 0  0 -3 -1 -1]
 [ 0  0 -1 -1 -1]
 [10 11 12 13 -3]
 [15 16 17 18 19]]


### Numerical and Algebrical Operations

In [46]:
# Comparisons

a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

print('---element-wise---')
print(a>b) 

print('---array-wise---')
print(np.array_equal(a,b)) 

---element-wise---
[False False  True False]
---array-wise---
False


In [54]:
# Reductions

C = np.zeros((10,10))
C[:] = np.arange(10)
print(C)

print('sum')
print(C.sum())
print(np.sum(C))

print('sum in a particular axis')
print(C.sum(axis=0))
print(C.sum(axis=1))

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]]
sum
450.0
450.0
sum in a particular axis
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90.]
[ 45.  45.  45.  45.  45.  45.  45.  45.  45.  45.]


In [57]:
# Matrix multiplication

H = np.linspace(0,1,25).reshape(5,5)
d = np.ones((5,1))

print('matrix vector multiplication')
print(np.dot(H,d))

print('Very different from H*d')
print(H*d)

print('dimensions should match')
print(np.dot(d,H))    # Error message since (5,1) can not multiply (5,5)

matrix vector multiplication
[[ 0.41666667]
 [ 1.45833333]
 [ 2.5       ]
 [ 3.54166667]
 [ 4.58333333]]
Very different from H*d
[[ 0.          0.04166667  0.08333333  0.125       0.16666667]
 [ 0.20833333  0.25        0.29166667  0.33333333  0.375     ]
 [ 0.41666667  0.45833333  0.5         0.54166667  0.58333333]
 [ 0.625       0.66666667  0.70833333  0.75        0.79166667]
 [ 0.83333333  0.875       0.91666667  0.95833333  1.        ]]


ValueError: shapes (5,1) and (5,5) not aligned: 1 (dim 1) != 5 (dim 0)

In [68]:
s = 10000
D = np.random.uniform(low=0,high=1,size=(s,s))
E = np.random.uniform(low=0,high=1,size=(s,s))
cProfile.run('F = D*E')

cProfile.run('G = np.multiply(D,E)')

np.set_printoptions(precision=4)
print(F[:6,:6])
print()
print(G[:6,:6])

         3 function calls in 0.482 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.482    0.482    0.482    0.482 <string>:1(<module>)
        1    0.000    0.000    0.482    0.482 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}


         3 function calls in 0.486 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.486    0.486    0.486    0.486 <string>:1(<module>)
        1    0.000    0.000    0.486    0.486 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}


[[ 0.4036  0.0671  0.2234  0.1687  0.1079  0.005 ]
 [ 0.3411  0.1706  0.124   0.0596  0.0321  0.1214]
 [ 0.0632  0.0395  0.729   0.3653  0.1841  0.0924]
 [ 0.6116  0.2726  0.2504  0.7321  0.557   0.5472]
 [ 0.1264  0.3694  0